services:

  # Postgres db
  postgres:
    image: postgres:18.1-bookworm
    container_name: IRKA_database
    ports:
      - "127.0.0.1:5432:5432" #! Development only, remove to make it container-only
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - datairka:/var/lib/postgresql/
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 3s
      timeout: 5s
      retries: 15
    restart: unless-stopped

  # FastAPI backend
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    container_name: IRKA_backend
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - ./backend:/app/backend # Hot-reload
    restart: unless-stopped
    command: ["uvicorn", "backend.main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"] #* Run in development environment 

  # Angular frontend
  frontend:
    image: node:22-bookworm
    container_name: IRKA_frontend
    working_dir: /app
    depends_on:
      - backend
    ports:
      - "4200:4200"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    restart: unless-stopped
    command: ["sh", "-c", "npm install && npx ng serve --host 0.0.0.0 --port 4200"]


volumes:
  datairka:
  redis-data:
    driver: local