"""Added tables for backfill worker and messages

Revision ID: 5ae9ad9a6af4
Revises: 07adf6f1713a
Create Date: 2026-04-23 21:08:25.725093

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5ae9ad9a6af4'
down_revision: Union[str, Sequence[str], None] = '07adf6f1713a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('backfilljob',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('channel_name', sa.VARCHAR(), nullable=False),
    sa.Column('channel_id', sa.BigInteger(), nullable=True),
    sa.Column('status', sa.VARCHAR(), nullable=False),
    sa.Column('progress_count', sa.Integer(), nullable=False),
    sa.Column('last_message_id', sa.BigInteger(), nullable=False),
    sa.Column('error', sa.VARCHAR(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('message',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('channel_id', sa.BigInteger(), nullable=False),
    sa.Column('message_id', sa.BigInteger(), nullable=False),
    sa.Column('text', sa.VARCHAR(), nullable=False),
    sa.Column('sender_id', sa.BigInteger(), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('channel_id', 'message_id', name='uq_channel_message')
    )
    op.create_index(op.f('ix_message_channel_id'), 'message', ['channel_id'], unique=False)
    op.create_index(op.f('ix_message_date'), 'message', ['date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_message_date'), table_name='message')
    op.drop_index(op.f('ix_message_channel_id'), table_name='message')
    op.drop_table('message')
    op.drop_table('backfilljob')
    # ### end Alembic commands ###
