"""initial

Revision ID: 5c31200e25f1
Revises: 
Create Date: 2026-05-01 12:30:17.697805

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5c31200e25f1'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('channel',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('title', sa.VARCHAR(), nullable=False),
    sa.Column('photo', sa.VARCHAR(), nullable=True),
    sa.Column('creator', sa.VARCHAR(), nullable=True),
    sa.Column('link', sa.VARCHAR(), nullable=True),
    sa.Column('channel_name', sa.VARCHAR(), nullable=False),
    sa.Column('message_count', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_channel_channel_name'), 'channel', ['channel_name'], unique=True)
    op.create_table('user',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('username', sa.VARCHAR(), nullable=True),
    sa.Column('password', sa.VARCHAR(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('backfilljob',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('channel_id', sa.BigInteger(), nullable=True),
    sa.Column('channel_name', sa.VARCHAR(), nullable=False),
    sa.Column('status', sa.VARCHAR(), nullable=False),
    sa.Column('progress_count', sa.Integer(), nullable=False),
    sa.Column('last_message_id', sa.BigInteger(), nullable=False),
    sa.Column('error', sa.VARCHAR(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['channel_id'], ['channel.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('message',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('channel_id', sa.BigInteger(), nullable=True),
    sa.Column('message_id', sa.BigInteger(), nullable=True),
    sa.Column('text', sa.VARCHAR(), nullable=False),
    sa.Column('sender_id', sa.BigInteger(), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['channel_id'], ['channel.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('channel_id', 'message_id', name='uq_channel_message')
    )
    op.create_index(op.f('ix_message_channel_id'), 'message', ['channel_id'], unique=False)
    op.create_index(op.f('ix_message_date'), 'message', ['date'], unique=False)
    op.create_table('monitorjob',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('channel_id', sa.BigInteger(), nullable=False),
    sa.Column('channel_name', sa.VARCHAR(), nullable=False),
    sa.Column('status', sa.VARCHAR(), nullable=False),
    sa.Column('error', sa.VARCHAR(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['channel_id'], ['channel.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('monitorjob')
    op.drop_index(op.f('ix_message_date'), table_name='message')
    op.drop_index(op.f('ix_message_channel_id'), table_name='message')
    op.drop_table('message')
    op.drop_table('backfilljob')
    op.drop_table('user')
    op.drop_index(op.f('ix_channel_channel_name'), table_name='channel')
    op.drop_table('channel')
    # ### end Alembic commands ###
