"""Added MonitorJob

Revision ID: 6daa68e466b2
Revises: 5ae9ad9a6af4
Create Date: 2026-04-29 21:12:51.070509

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6daa68e466b2'
down_revision: Union[str, Sequence[str], None] = '5ae9ad9a6af4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('monitorjob',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('channel_name', sa.VARCHAR(), nullable=False),
    sa.Column('channel_id', sa.BigInteger(), nullable=True),
    sa.Column('status', sa.VARCHAR(), nullable=False),
    sa.Column('error', sa.VARCHAR(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('monitorjob')
    # ### end Alembic commands ###
